### ISSUE TITLE
I'm not even trying to use GPU, but I get CUDA errors

### ISSUE THREAD

**Issue by sanasigma** [s0md3v/roop#148]
![image](https://github.com/s0md3v/roop/assets/36327461/f8afbf6e-6c81-4979-b2d7-5e04d8d2b887)

EP Error D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1131 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\SORAM\AppData\Local\Programs\Python\Python310\lib\site-packages\onnxruntime\capi\onnxruntime_providers_tensorrt.dll"
 when using ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
EP Error D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1131 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\SORAM\AppData\Local\Programs\Python\Python310\lib\site-packages\onnxruntime\capi\onnxruntime_providers_tensorrt.dll"
 when using ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
EP Error D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1131 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\SORAM\AppData\Local\Programs\Python\Python310\lib\site-packages\onnxruntime\capi\onnxruntime_providers_tensorrt.dll"
 when using ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
EP Error D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1131 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\SORAM\AppData\Local\Programs\Python\Python310\lib\site-packages\onnxruntime\capi\onnxruntime_providers_tensorrt.dll"
 when using ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
EP Error D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1131 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\SORAM\AppData\Local\Programs\Python\Python310\lib\site-packages\onnxruntime\capi\onnxruntime_providers_tensorrt.dll"
 when using ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
EP Error D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1131 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\SORAM\AppData\Local\Programs\Python\Python310\lib\site-packages\onnxruntime\capi\onnxruntime_providers_tensorrt.dll"
 when using ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.

**Comment by Moeblack** [comment]
https://github.com/s0md3v/roop/issues/125#issuecomment-1569346077

**Comment by Moeblack** [comment]
https://github.com/s0md3v/roop/issues/125#issuecomment-1569346077

**Comment by FurkanGozukara** [comment]
interesting it is working fine with me - when no gpu used

i have rtx 3090 

have you followed my tutorial?

34.) PC - Google Colab - Free

[**Mind-Blowing Deepfake Tutorial: Turn Anyone into Your Favorite Movie Star! PC & Google Colab - roop**](https://youtu.be/OI1LEN-SgLM)

[![image](https://github.com/FurkanGozukara/Stable-Diffusion/assets/19240467/4ce2ccf1-e5fd-4afd-a7ff-a8b65b69adc6)](https://youtu.be/OI1LEN-SgLM)

**Comment by adithya-s-sekhar** [comment]
Same error here.

**Comment by adithya-s-sekhar** [comment]
![Screenshot 2023-05-31 100806](https://github.com/s0md3v/roop/assets/60822601/8decb544-6ad2-4e6d-99fd-10be15d1e179)

It's trying repeatedly to run on CUDA even though I didn't give a --gpu flag.

**Comment by ohmygoobness** [comment]
is this because of onnxruntime-gpu? uninstall onnxruntime-gpu and install onnxruntime

**Comment by adithya-s-sekhar** [comment]
@ohmygoobness thank you, that helped it start. But now it crashes in the middle of swapping. I think this is a different issue now.

```
inswapper-shape: [1, 3, 128, 128]
............................................................Process ForkPoolWorker-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 131, in worker
    put((job, i, result))
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 377, in put
    self._writer.send_bytes(obj)
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 377, in put
    self._writer.send_bytes(obj)
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by adithya-s-sekhar** [comment]
I still have an older copy of the repo updated till https://github.com/s0md3v/roop/commit/de7d384bcaaeb20b08721929f09bb52ab9818d3f

This works flawlessly for me without gpu.

**Comment by ohmygoobness** [comment]
@adithya-s-sekhar can you use the latest fork but edit the
video_name = target_path.split("/")[-1].split(".")[0]
output_dir = target_path.replace(target_path.split("/")[-1], "").rstrip("/") + "/" + video_name

**Comment by henryruhs** [comment]
Should be fixed via https://github.com/s0md3v/roop/pull/151

**Comment by adithya-s-sekhar** [comment]
> @adithya-s-sekhar can you use the latest fork but edit the video_name = target_path.split("/")[-1].split(".")[0] output_dir = target_path.replace(target_path.split("/")[-1], "").rstrip("/") + "/" + video_name

It didn't work. Crashed with this error.
<img width="675" alt="Screenshot 2023-05-31 125658" src="https://github.com/s0md3v/roop/assets/60822601/14708390-eebc-4530-8a79-b9692c911619">

The latest fork without any modifications works for swapping images. Videos starts to work but crashes halfway with a broken pipe error with this same message https://github.com/s0md3v/roop/issues/148#issuecomment-1569549142 .
