### ISSUE TITLE
GPU acceleration not working for Applie Silicon Macs

### ISSUE THREAD

**Issue by kelvinthh** [s0md3v/roop#162]
**Describe the bug**
GPU is not utilized during video generation as mentioned [here](https://github.com/s0md3v/roop/issues/154#issuecomment-1569525572) 
Python version: 3.10.11
Macbook Pro 2021 14"
macOS 13.4 Ventura

**To Reproduce**
- Scenario 1: Fresh virtual env, done `pip install -r requirements.txt`, with or without `--gpu` argument it will run without any issue, but it seems it's not using the Apple GPU anyway, I have the GPU usage window opened and witnessed no spike.
- Scenario 2: After `pip install -r requirements.txt`, I uninstalled the normal onnxruntime and `pip install onnxruntime-silicon`, I would then get a CUDA not available error.
- Scenario 3: Almost the same with scenario 2 but did not uninstall onnxruntime instead. Still got the CUDA not available error.

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [ ] Windows 
- [x] Mac

Are you try to use a GPU?
- [x] No. I am not using the `---gpu` flag
- [ ] NVIDIA
- [ ] AMD
- [ ] Intel
- [x] Mac

**Sanity Check**
- [x] I have the latest code from the github repository
- [x] I have followed the installation guide

**Comment by kyteague** [comment]
I have this working locally but CoreML doesn't work for the face swapping insightface model anyways. Seems to be an issue with the ONNX runtime or coremltools. The model runs but the face ends up being garbled.

**Comment by henryruhs** [comment]
See https://github.com/s0md3v/roop/issues/154#issuecomment-1569525572

**Comment by kelvinthh** [comment]
Also I'd like to add that building `onnxruntime-silicon` as mentioned in the wiki for Mac GPU acceleration is not buildable. The build will fail possibly due to some dependency issues that come with the aging package. The best one can do is install it via `pip install onnxruntime-silicon` but as mentioned above it will prompt you with a CUDA error.

**Comment by kyteague** [comment]
> Also I'd like to add that building `onnxruntime-silicon` as mentioned in the wiki for Mac GPU acceleration is not buildable. The build will fail possibly due to some dependency issues that come with the aging package. The best one can do is install it via `pip install onnxruntime-silicon` but as mentioned above it will prompt you with a CUDA error.

You need to use this branch for now for Xcode 14.3: https://github.com/microsoft/onnxruntime/tree/edgchen1/fix_mac_build_issues

**Comment by s0md3v** [comment]
@kelvinthh this issue should be fixed now, can you check?

**Comment by kelvinthh** [comment]
> @kelvinthh this issue should be fixed now, can you check?

Just checked and it works fine, but the memory limit is still a pain, you'd need to set the `--max-memory` value to a unreasonable amount to make it run, I usually set it to somewhere over 1000 for generating a 700 frames video so it won't get killed by the OS , but I don't think it is something we can do about at the moment.
![memory limit](https://github.com/s0md3v/roop/assets/3705865/64e0075e-6b7d-4210-80f2-d5e66b2105a0)

Also the default `requirements.txt` doesn't play well with Apple silicon Macs when doing `pip install -r requirements.txt` with errors, so I dumped my fresh virtual env's with `pip freeze > requirements_mac.txt` [requirements_mac.txt](https://gist.github.com/kelvinthh/52c6dabba8ccc05123b7614c71033ba2), it should play nice with any M1/M2 Mac without any error under a Python 3.10 environment.

**Comment by henryruhs** [comment]
Over 1000? That flag is meant to be in GB...

https://github.com/s0md3v/roop/blob/main/run.py#L54-L58

**Comment by erich2s** [comment]
> Over 1000? That flag is meant to be in GB...
> 
> https://github.com/s0md3v/roop/blob/main/run.py#L60-L61

Maybe it's Mac OS's problem...They use a different memory management system than previous generations of Macs?
![iShot_2023-06-01_20 43 48](https://github.com/s0md3v/roop/assets/53571741/f4f1deca-bc47-411f-b26e-ca41805c0a23)

**Comment by henryruhs** [comment]
We just pushed a fix according to MQ dependencies. Give it a shot

**Comment by uPagge** [comment]
@kelvinthh Можешь подсказать что нужно закомментировать, у меня определяется только CPUExecutionProvider

**Comment by uPagge** [comment]
@kelvinthh Can you tell me what to comment on, I only have CPUExecutionProvider

**Comment by huseyinzorlu** [comment]
@uPagge you can use Docker container to handle overdose memory issue. I used below configuration on my side
Dockerfile
FROM python:3.9

WORKDIR /app

RUN apt-get update && apt-get install -y \
    git \
    ffmpeg

RUN pip install --upgrade pip

# CMD [ "/bin/bash" ]
CMD ["tail", "-f", "/dev/null"]

docker-compose.yml
version: '3.8'

services:
  df:
    build: 
      context: .
      dockerfile: Dockerfile
    # command: /bin/bash
    command: tail -f /dev/null
    volumes:
      - ./:/app
    mem_limit: 40g

how to run ?
1.docker-compose up -d 
2. docker-compose exec df bash

after this you can type command and use without any overdose RAM issue on M1 Macbook

**Comment by kelvinthh** [comment]
> [ARM MAC M1 CHIP]ERROR: No matching distribution found for onnxruntime-gpu #154

But do you get CoreML acceleration with Docker?

**Comment by masami87** [comment]
I seem to have also encountered memory issues when using GPU mode on my Mac. Using the --gpu option does indeed accelerate the process, but I had to cut the video down to less than 10 seconds in order to prevent the program from being killed.

**Comment by henryruhs** [comment]
I added CoreMLExecutionProvider support for Apple Silicon via https://github.com/s0md3v/roop/actions/runs/5167966332! to the next branch!

Dependencies should not be resolved correct as of updated `requirements.txt`. Make sure to uninstall `onnxruntime` and `onnxruntime-silicon` before you reinstall it all.

Run with new `--gpu-vendor` flag:

```
./run.py -f=.github/examples/face.jpg -t=.github/examples/target.mp4 -o=.github/examples/output.mp4 --gpu-vendor=apple
```

Although the `CoreMLExecutionProvider` is in my provider list it is not being applied on my machine. I keep this issue open until someone reports that CoreML works.

**Comment by jjangga0214** [comment]
@henryruhs I tried it on the `next` branch by following your instruction (uninstalled and reinstalled the (entire) deps). However it still only uses CPUs on M1 MAX. Maybe we should reopen the issue?

**Comment by henryruhs** [comment]
Try:

```
./run.py --gpu-vendor=apple --gpu-threads=32
``
