### ISSUE TITLE
GPU problem --gpu not working

### ISSUE THREAD

**Issue by kex0** [s0md3v/roop#43]
Making new issue because previous issues are a mess.

The problem I have is that whenever I use `--gpu` argument I frequently get out of memory errors and nothing get's done.
Sometimes the process doesn't even get to the part where it extracts frames and I just get spammed by errors like this
[output.txt](https://github.com/s0md3v/roop/files/11593494/output.txt)
and this:
![Taskmgr_xKTca3cN9c](https://github.com/s0md3v/roop/assets/46696708/490e5168-d114-4eda-88cd-9da521a3fb98)

Sometimes only a couple of frames get face swapped (not even sure if it's done using GPU) and then it just spams errors.

My screen is sometimes blinking, probably because I'm getting out of GPU memory.

And sometimes I just get BSOD straight up.

P.S. the windows paths finally work

RTX4090
5900X
128GB RAM

Win11 (no WSL)
CUDA 11.8
cuDNN 8.9.1

**Comment by s0md3v** [comment]
This seems to be an issue in onnxruntime. I technically doesn't concern me but I will try to help you regardless.

You have seen such output in your terminal right? (of course, CUDA instead of ROCM)
```
Applied providers: ['ROCMExecutionProvider', 'CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}, 'ROCMExecutionProvider': {'tunable_op_tuning_enable': '0', 'tunable_op_enable': '0', 'miopen_conv_exhaustive_search': '0', 'do_copy_in_default_stream': '1', 'arena_extend_strategy': 'kNextPowerOfTwo', 'gpu_external_empty_cache': '0', 'gpu_external_free': '0', 'gpu_external_alloc': '0', 'gpu_mem_limit': '18446744073709551615', 'miopen_conv_use_max_workspace': '1', 'device_id': '0'}}
```

Go to `run.py` and add these options [here](https://github.com/s0md3v/roop/blob/be3a4e8ebd1f3dab5e80ff5adf033f1a992790c7/run.py#L10) like this:

```
if '--gpu' not in sys.argv:
    core.globals.providers = ['CPUExecutionProvider']
core.globals.providers = [
    ('ROCMExecutionProvider', {
        'device_id': '0',
        'gpu_mem_limit': '14446744073709551615',
        ...more options...
    })
]
```

Once you have done that, check out these docs to see what each option does and try to change them around: https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#configuration-options

I would personally suggest starting with setting `cudnn_conv_algo_search` to `HEURISTIC`.

**Comment by FurkanGozukara** [comment]
I am getting this error

trying to install tensorrt on windows python but couldnt yet


installed torch 1.13


```
(venv) F:\roop>python run.py --gpu
EP Error D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1131 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "F:\roop\venv\lib\site-packages\onnxruntime\capi\onnxruntime_providers_tensorrt.dll"
 when using ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
2023-05-30 00:19:09.4596725 [E:onnxruntime:Default, provider_bridge_ort.cc:1351 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1131 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "F:\roop\venv\lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

Traceback (most recent call last):
  File "F:\roop\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 383, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "F:\roop\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 435, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError: D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1131 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "F:\roop\venv\lib\site-packages\onnxruntime\capi\onnxruntime_providers_tensorrt.dll"


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\roop\run.py", line 19, in <module>
    from core.processor import process_video, process_img
  File "F:\roop\core\processor.py", line 5, in <module>
    from core.config import get_face
  File "F:\roop\core\config.py", line 5, in <module>
    face_analyser = insightface.app.FaceAnalysis(name='buffalo_l', providers=core.globals.providers)
  File "F:\roop\venv\lib\site-packages\insightface\app\face_analysis.py", line 31, in __init__
    model = model_zoo.get_model(onnx_file, **kwargs)
  File "F:\roop\venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 96, in get_model
    model = router.get_model(providers=providers, provider_options=provider_options)
  File "F:\roop\venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 40, in get_model
    session = PickableInferenceSession(self.onnx_file, **kwargs)
  File "F:\roop\venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 25, in __init__
    super().__init__(model_path, **kwargs)
  File "F:\roop\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 394, in __init__
    raise fallback_error from e
  File "F:\roop\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 389, in __init__
    self._create_inference_session(self._fallback_providers, None)
  File "F:\roop\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 435, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError: D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:636 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.

```

**Comment by henryruhs** [comment]
I solved it, PR is coming.

**Comment by FurkanGozukara** [comment]
> I solved it, PR is coming.

awesome

**Comment by FurkanGozukara** [comment]
@henryruhs i hope you can make pull request before going to sleep :D

**Comment by henryruhs** [comment]
My wife hates me for that, but I did it :D

**Comment by FurkanGozukara** [comment]
> Done

awesome

my wife also complaining me haha :d

**Comment by s0md3v** [comment]
We just released a patch for this issue, try again with the latest changes. I also suggest installing this exact version of onnxruntime-gpu as follows:

```
pip uninstall onnxruntime
pip install onnxruntime-gpu==1.15.0
```

**Comment by henryruhs** [comment]
It is possible that you need to uninstall both packages.

**Comment by kex0** [comment]
This did not solve my issue. I even had to reinstall torch to CUDA version for `--gpu` to work.
'gpu_mem_limit': seems to have no effect, and I tried to play with other options but with no success. I either get BSOD after 2 seconds or there's no change and I still get error spam.

**Comment by s0md3v** [comment]
@kex0 https://github.com/s0md3v/roop/issues/56#issuecomment-1567623208

**Comment by kex0** [comment]
I do have cuDNN

> Win11 (no WSL)
> CUDA 11.8
> cuDNN 8.9.1

**Comment by kex0** [comment]
Doing this
```
core.globals.providers = [
    ('CUDAExecutionProvider', {
        'device_id': '0',
        'gpu_mem_limit': '1444674400',
        'cudnn_conv_algo_search': 'HEURISTIC'
    })
]
```
Allows me to generate like 50-60 frames incredibly quickly (GPU works) but then it fills up memory anyways and it starts spamming errors or gives me BSOD

**Comment by phineas-pta** [comment]
for me, setting `'cudnn_conv_algo_search': 'HEURISTIC'`doesn't speed up

the speed is also very unstable, sometimes >10 frame/s but often 1-2 frame/s

i've tried reinstall but it doesn't change
