### ISSUE TITLE
CUDA Error, can't use GPU. CUDA is installed.

### ISSUE THREAD

**Issue by fredrickflower** [s0md3v/roop#56]
O:\roop>python run.py --gpu
EP Error D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1131 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "O:\Python\lib\site-packages\onnxruntime\capi\onnxruntime_providers_tensorrt.dll"
 when using ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
2023-05-30 01:17:03.2715876 [E:onnxruntime:Default, provider_bridge_ort.cc:1351 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1131 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "O:\Python\lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

Traceback (most recent call last):
  File "O:\Python\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 383, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "O:\Python\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 435, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError: D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1131 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "O:\Python\lib\site-packages\onnxruntime\capi\onnxruntime_providers_tensorrt.dll"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "O:\roop\run.py", line 22, in <module>
    from core.processor import process_video, process_img
  File "O:\roop\core\processor.py", line 5, in <module>
    from core.config import get_face
  File "O:\roop\core\config.py", line 4, in <module>
    face_analyser = insightface.app.FaceAnalysis(name='buffalo_l', providers=core.globals.providers)
  File "O:\Python\lib\site-packages\insightface\app\face_analysis.py", line 31, in __init__
    model = model_zoo.get_model(onnx_file, **kwargs)
  File "O:\Python\lib\site-packages\insightface\model_zoo\model_zoo.py", line 96, in get_model
    model = router.get_model(providers=providers, provider_options=provider_options)
  File "O:\Python\lib\site-packages\insightface\model_zoo\model_zoo.py", line 40, in get_model
    session = PickableInferenceSession(self.onnx_file, **kwargs)
  File "O:\Python\lib\site-packages\insightface\model_zoo\model_zoo.py", line 25, in __init__
    super().__init__(model_path, **kwargs)
  File "O:\Python\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 394, in __init__
    raise fallback_error from e
  File "O:\Python\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 389, in __init__
    self._create_inference_session(self._fallback_providers, None)
  File "O:\Python\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 435, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError: D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:636 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.

**Comment by fredrickflower** [comment]
I am new to this so I could be doing something wrong but I have CUDA installed on my system and yet I can't use GPU on this program.

**Comment by s0md3v** [comment]
@fredrickflower we pushed a patch to fix this a couple of minutes ago. Do you have the latest code?

**Comment by fredrickflower** [comment]
Yes I do.

**Comment by adam-andrzejczak** [comment]
Uninstall onnxruntime, onnxruntime-gpu and onnx. Then install 2 and 3.

**Comment by fredrickflower** [comment]
Sorry hate to be dumb, but what do you mean by 2 and 3?

**Comment by s0md3v** [comment]
@fredrickflower onnxruntime-gpu and onnx

**Comment by fredrickflower** [comment]
Reinstalled but got same error. It's using the cached files to install though, not sure if that's an issue,

**Comment by pablodawson** [comment]
you need cuDNN installed too if I'm not mistaken (+cuda toolkit if you don't have it):
https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html

**Comment by adam-andrzejczak** [comment]
@s0md3v in requirements.txt you have onnxruntime instead of onnxruntime-gpu, thats what causing CPU provider to be available only while calling onnxruntime.get_available_providers()

**Comment by s0md3v** [comment]
@adam-andrzejczak okay, removed it :/

**Comment by henryruhs** [comment]
Why not onnxruntime-gpu in the `requirements.txt` - like I said, this should work for CPU and GPU.

**Comment by fredrickflower** [comment]
Seems I didn't have CUDNN installed properly. But now I have this error:

O:\roop>python run.py --gpu
EP Error D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1131 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "O:\Python\lib\site-packages\onnxruntime\capi\onnxruntime_providers_tensorrt.dll"
 when using ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CUDAExecutionProvider': {'do_copy_in_default_stream': '1', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'device_id': '0', 'gpu_external_alloc': '0', 'enable_cuda_graph': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'cudnn_conv_use_max_workspace': '1', 'cudnn_conv1d_pad_to_nc1d': '0', 'tunable_op_enable': '0', 'tunable_op_tuning_enable': '0', 'enable_skip_layer_norm_strict_mode': '0'}, 'CPUExecutionProvider': {}}
find model: C:\Users\Reece/.insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
EP Error D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1131 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "O:\Python\lib\site-packages\onnxruntime\capi\onnxruntime_providers_tensorrt.dll"
 when using ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CUDAExecutionProvider': {'do_copy_in_default_stream': '1', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'device_id': '0', 'gpu_external_alloc': '0', 'enable_cuda_graph': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'cudnn_conv_use_max_workspace': '1', 'cudnn_conv1d_pad_to_nc1d': '0', 'tunable_op_enable': '0', 'tunable_op_tuning_enable': '0', 'enable_skip_layer_norm_strict_mode': '0'}, 'CPUExecutionProvider': {}}
find model: C:\Users\Reece/.insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
EP Error D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1131 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "O:\Python\lib\site-packages\onnxruntime\capi\onnxruntime_providers_tensorrt.dll"
 when using ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CUDAExecutionProvider': {'do_copy_in_default_stream': '1', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'device_id': '0', 'gpu_external_alloc': '0', 'enable_cuda_graph': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'cudnn_conv_use_max_workspace': '1', 'cudnn_conv1d_pad_to_nc1d': '0', 'tunable_op_enable': '0', 'tunable_op_tuning_enable': '0', 'enable_skip_layer_norm_strict_mode': '0'}, 'CPUExecutionProvider': {}}
find model: C:\Users\Reece/.insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
EP Error D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1131 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "O:\Python\lib\site-packages\onnxruntime\capi\onnxruntime_providers_tensorrt.dll"
 when using ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CUDAExecutionProvider': {'do_copy_in_default_stream': '1', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'device_id': '0', 'gpu_external_alloc': '0', 'enable_cuda_graph': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'cudnn_conv_use_max_workspace': '1', 'cudnn_conv1d_pad_to_nc1d': '0', 'tunable_op_enable': '0', 'tunable_op_tuning_enable': '0', 'enable_skip_layer_norm_strict_mode': '0'}, 'CPUExecutionProvider': {}}
find model: C:\Users\Reece/.insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
EP Error D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1131 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "O:\Python\lib\site-packages\onnxruntime\capi\onnxruntime_providers_tensorrt.dll"
 when using ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CUDAExecutionProvider': {'do_copy_in_default_stream': '1', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'device_id': '0', 'gpu_external_alloc': '0', 'enable_cuda_graph': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'cudnn_conv_use_max_workspace': '1', 'cudnn_conv1d_pad_to_nc1d': '0', 'tunable_op_enable': '0', 'tunable_op_tuning_enable': '0', 'enable_skip_layer_norm_strict_mode': '0'}, 'CPUExecutionProvider': {}}
find model: C:\Users\Reece/.insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
EP Error D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1131 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "O:\Python\lib\site-packages\onnxruntime\capi\onnxruntime_providers_tensorrt.dll"
 when using ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CUDAExecutionProvider': {'do_copy_in_default_stream': '1', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'device_id': '0', 'gpu_external_alloc': '0', 'enable_cuda_graph': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'cudnn_conv_use_max_workspace': '1', 'cudnn_conv1d_pad_to_nc1d': '0', 'tunable_op_enable': '0', 'tunable_op_tuning_enable': '0', 'enable_skip_layer_norm_strict_mode': '0'}, 'CPUExecutionProvider': {}}
inswapper-shape: [1, 3, 128, 128]
usage: run.py [-h] [-f SOURCE_IMG] [-t TARGET_PATH] [-o OUTPUT_FILE] [--keep-fps] [--keep-frames]
run.py: error: unrecognized arguments: --gpu

**Comment by adam-andrzejczak** [comment]
I have this situation, I can select picture, clip and target name, but then this strange log with extra commas appear and no frames are generated and my PC almost freezes.

PS U:\ai\df\roop-main> python run.py --gpu
Applied providers: ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'TensorrtExecutionProvider': {'trt_engine_cache_path': '', 'trt_int8_use_native_calibration_table': '0', 'trt_int8_calibration_table_name': '', 'device_id': '0', 'trt_max_partition_iterations': '1000', 'trt_force_sequential_engine_build': '0', 'trt_min_subgraph_size': '1', 'trt_max_workspace_size': '1073741824', 'trt_fp16_enable': '0', 'trt_int8_enable': '0', 'trt_dla_enable': '0', 'trt_dla_core': '0', 'trt_dump_subgraphs': '0', 'trt_engine_cache_enable': '0', 'trt_engine_decryption_enable': '0', 'trt_engine_decryption_lib_path': '', 'trt_context_memory_sharing_enable': '0', 'trt_layer_norm_fp32_fallback': '0', 'trt_timing_cache_enable': '0', 'trt_force_timing_cache_match': '0', 'trt_profile_opt_shapes': '', 'trt_detailed_build_log': '0', 'trt_build_heuristics_enable': '0', 'trt_sparsity_enable': '0', 'trt_builder_optimization_level': '3', 'trt_auxiliary_streams': '-1', 'trt_tactic_sources': '', 'trt_extra_plugin_lib_paths': '', 'trt_profile_min_shapes': '', 'trt_profile_max_shapes': ''}, 'CUDAExecutionProvider': {'do_copy_in_default_stream': '1', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'device_id': '0', 'gpu_external_alloc': '0', 'enable_cuda_graph': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'cudnn_conv_use_max_workspace': '1', 'cudnn_conv1d_pad_to_nc1d': '0', 'tunable_op_enable': '0', 'tunable_op_tuning_enable': '0', 'enable_skip_layer_norm_strict_mode': '0'}, 'CPUExecutionProvider': {}}
find model: C:\Users\archo/.insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'TensorrtExecutionProvider': {'trt_engine_cache_path': '', 'trt_int8_use_native_calibration_table': '0', 'trt_int8_calibration_table_name': '', 'device_id': '0', 'trt_max_partition_iterations': '1000', 'trt_force_sequential_engine_build': '0', 'trt_min_subgraph_size': '1', 'trt_max_workspace_size': '1073741824', 'trt_fp16_enable': '0', 'trt_int8_enable': '0', 'trt_dla_enable': '0', 'trt_dla_core': '0', 'trt_dump_subgraphs': '0', 'trt_engine_cache_enable': '0', 'trt_engine_decryption_enable': '0', 'trt_engine_decryption_lib_path': '', 'trt_context_memory_sharing_enable': '0', 'trt_layer_norm_fp32_fallback': '0', 'trt_timing_cache_enable': '0', 'trt_force_timing_cache_match': '0', 'trt_profile_opt_shapes': '', 'trt_detailed_build_log': '0', 'trt_build_heuristics_enable': '0', 'trt_sparsity_enable': '0', 'trt_builder_optimization_level': '3', 'trt_auxiliary_streams': '-1', 'trt_tactic_sources': '', 'trt_extra_plugin_lib_paths': '', 'trt_profile_min_shapes': '', 'trt_profile_max_shapes': ''}, 'CUDAExecutionProvider': {'do_copy_in_default_stream': '1', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'device_id': '0', 'gpu_external_alloc': '0', 'enable_cuda_graph': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'cudnn_conv_use_max_workspace': '1', 'cudnn_conv1d_pad_to_nc1d': '0', 'tunable_op_enable': '0', 'tunable_op_tuning_enable': '0', 'enable_skip_layer_norm_strict_mode': '0'}, 'CPUExecutionProvider': {}}
find model: C:\Users\archo/.insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'TensorrtExecutionProvider': {'trt_engine_cache_path': '', 'trt_int8_use_native_calibration_table': '0', 'trt_int8_calibration_table_name': '', 'device_id': '0', 'trt_max_partition_iterations': '1000', 'trt_force_sequential_engine_build': '0', 'trt_min_subgraph_size': '1', 'trt_max_workspace_size': '1073741824', 'trt_fp16_enable': '0', 'trt_int8_enable': '0', 'trt_dla_enable': '0', 'trt_dla_core': '0', 'trt_dump_subgraphs': '0', 'trt_engine_cache_enable': '0', 'trt_engine_decryption_enable': '0', 'trt_engine_decryption_lib_path': '', 'trt_context_memory_sharing_enable': '0', 'trt_layer_norm_fp32_fallback': '0', 'trt_timing_cache_enable': '0', 'trt_force_timing_cache_match': '0', 'trt_profile_opt_shapes': '', 'trt_detailed_build_log': '0', 'trt_build_heuristics_enable': '0', 'trt_sparsity_enable': '0', 'trt_builder_optimization_level': '3', 'trt_auxiliary_streams': '-1', 'trt_tactic_sources': '', 'trt_extra_plugin_lib_paths': '', 'trt_profile_min_shapes': '', 'trt_profile_max_shapes': ''}, 'CUDAExecutionProvider': {'do_copy_in_default_stream': '1', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'device_id': '0', 'gpu_external_alloc': '0', 'enable_cuda_graph': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'cudnn_conv_use_max_workspace': '1', 'cudnn_conv1d_pad_to_nc1d': '0', 'tunable_op_enable': '0', 'tunable_op_tuning_enable': '0', 'enable_skip_layer_norm_strict_mode': '0'}, 'CPUExecutionProvider': {}}
find model: C:\Users\archo/.insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'TensorrtExecutionProvider': {'trt_engine_cache_path': '', 'trt_int8_use_native_calibration_table': '0', 'trt_int8_calibration_table_name': '', 'device_id': '0', 'trt_max_partition_iterations': '1000', 'trt_force_sequential_engine_build': '0', 'trt_min_subgraph_size': '1', 'trt_max_workspace_size': '1073741824', 'trt_fp16_enable': '0', 'trt_int8_enable': '0', 'trt_dla_enable': '0', 'trt_dla_core': '0', 'trt_dump_subgraphs': '0', 'trt_engine_cache_enable': '0', 'trt_engine_decryption_enable': '0', 'trt_engine_decryption_lib_path': '', 'trt_context_memory_sharing_enable': '0', 'trt_layer_norm_fp32_fallback': '0', 'trt_timing_cache_enable': '0', 'trt_force_timing_cache_match': '0', 'trt_profile_opt_shapes': '', 'trt_detailed_build_log': '0', 'trt_build_heuristics_enable': '0', 'trt_sparsity_enable': '0', 'trt_builder_optimization_level': '3', 'trt_auxiliary_streams': '-1', 'trt_tactic_sources': '', 'trt_extra_plugin_lib_paths': '', 'trt_profile_min_shapes': '', 'trt_profile_max_shapes': ''}, 'CUDAExecutionProvider': {'do_copy_in_default_stream': '1', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'device_id': '0', 'gpu_external_alloc': '0', 'enable_cuda_graph': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'cudnn_conv_use_max_workspace': '1', 'cudnn_conv1d_pad_to_nc1d': '0', 'tunable_op_enable': '0', 'tunable_op_tuning_enable': '0', 'enable_skip_layer_norm_strict_mode': '0'}, 'CPUExecutionProvider': {}}
find model: C:\Users\archo/.insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'TensorrtExecutionProvider': {'trt_engine_cache_path': '', 'trt_int8_use_native_calibration_table': '0', 'trt_int8_calibration_table_name': '', 'device_id': '0', 'trt_max_partition_iterations': '1000', 'trt_force_sequential_engine_build': '0', 'trt_min_subgraph_size': '1', 'trt_max_workspace_size': '1073741824', 'trt_fp16_enable': '0', 'trt_int8_enable': '0', 'trt_dla_enable': '0', 'trt_dla_core': '0', 'trt_dump_subgraphs': '0', 'trt_engine_cache_enable': '0', 'trt_engine_decryption_enable': '0', 'trt_engine_decryption_lib_path': '', 'trt_context_memory_sharing_enable': '0', 'trt_layer_norm_fp32_fallback': '0', 'trt_timing_cache_enable': '0', 'trt_force_timing_cache_match': '0', 'trt_profile_opt_shapes': '', 'trt_detailed_build_log': '0', 'trt_build_heuristics_enable': '0', 'trt_sparsity_enable': '0', 'trt_builder_optimization_level': '3', 'trt_auxiliary_streams': '-1', 'trt_tactic_sources': '', 'trt_extra_plugin_lib_paths': '', 'trt_profile_min_shapes': '', 'trt_profile_max_shapes': ''}, 'CUDAExecutionProvider': {'do_copy_in_default_stream': '1', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'device_id': '0', 'gpu_external_alloc': '0', 'enable_cuda_graph': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'cudnn_conv_use_max_workspace': '1', 'cudnn_conv1d_pad_to_nc1d': '0', 'tunable_op_enable': '0', 'tunable_op_tuning_enable': '0', 'enable_skip_layer_norm_strict_mode': '0'}, 'CPUExecutionProvider': {}}
find model: C:\Users\archo/.insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
[libprotobuf WARNING **************************************************************************\externals\protobuf\3.0.0\src\google\protobuf\io\coded_stream.cc:604] Reading dangerously large protocol message.  If the message turns out to be larger than 2147483647 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING **************************************************************************\externals\protobuf\3.0.0\src\google\protobuf\io\coded_stream.cc:81] The total number of bytes read was 553206116
[libprotobuf WARNING **************************************************************************\externals\protobuf\3.0.0\src\google\protobuf\io\coded_stream.cc:604] Reading dangerously large protocol message.  If the message turns out to be larger than 2147483647 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING **************************************************************************\externals\protobuf\3.0.0\src\google\protobuf\io\coded_stream.cc:81] The total number of bytes read was 553206116
[libprotobuf WARNING **************************************************************************\externals\protobuf\3.0.0\src\google\protobuf\io\coded_stream.cc:604] Reading dangerously large protocol message.  If the message turns out to be larger than 2147483647 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING **************************************************************************\externals\protobuf\3.0.0\src\google\protobuf\io\coded_stream.cc:81] The total number of bytes read was 553206705
Applied providers: ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'TensorrtExecutionProvider': {'trt_engine_cache_path': '', 'trt_int8_use_native_calibration_table': '0', 'trt_int8_calibration_table_name': '', 'device_id': '0', 'trt_max_partition_iterations': '1000', 'trt_force_sequential_engine_build': '0', 'trt_min_subgraph_size': '1', 'trt_max_workspace_size': '1073741824', 'trt_fp16_enable': '0', 'trt_int8_enable': '0', 'trt_dla_enable': '0', 'trt_dla_core': '0', 'trt_dump_subgraphs': '0', 'trt_engine_cache_enable': '0', 'trt_engine_decryption_enable': '0', 'trt_engine_decryption_lib_path': '', 'trt_context_memory_sharing_enable': '0', 'trt_layer_norm_fp32_fallback': '0', 'trt_timing_cache_enable': '0', 'trt_force_timing_cache_match': '0', 'trt_profile_opt_shapes': '', 'trt_detailed_build_log': '0', 'trt_build_heuristics_enable': '0', 'trt_sparsity_enable': '0', 'trt_builder_optimization_level': '3', 'trt_auxiliary_streams': '-1', 'trt_tactic_sources': '', 'trt_extra_plugin_lib_paths': '', 'trt_profile_min_shapes': '', 'trt_profile_max_shapes': ''}, 'CUDAExecutionProvider': {'do_copy_in_default_stream': '1', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'device_id': '0', 'gpu_external_alloc': '0', 'enable_cuda_graph': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'cudnn_conv_use_max_workspace': '1', 'cudnn_conv1d_pad_to_nc1d': '0', 'tunable_op_enable': '0', 'tunable_op_tuning_enable': '0', 'enable_skip_layer_norm_strict_mode': '0'}, 'CPUExecutionProvider': {}}
inswapper-shape: [1, 3, 128, 128]
DON'T WORRY. IT'S NOT STUCK/CRASHED.
DON'T WORRY. IT'S NOT STUCK/CRASHED.
DON'T WORRY. IT'S NOT STUCK/CRASHED.
DON'T WORRY. IT'S NOT STUCK/CRASHED.
DON'T WORRY. IT'S NOT STUCK/CRASHED.

2 0 2 3 - 0 5 - 3 0   0 3 : 2 1 : 4 2 . 2 3 1 6 3 8 3   [ E : o n n x r u n t i m e : D e f a u l t ,   t e n s o r r t _ e x e c u t i o n _ p r o v i d e r . h : 7 3   o n n x r u n t i m e : : T e n s o r r t L o g g e r : : l o g ]   [ 2 0 2 3 - 0 5 - 3 0   0 1 : 2 1 : 4 2       E R R O R ]   1 :   [ v i r t u a l M e m o r y B u f f e r . c p p : : n v i n f e r 1 : : S t d V i r t u a l M e m o r y B u f f e r I m p l : : r e s i z e P h y s i c a l : : 1 2 7 ]   E r r o r   C o d e   1 :   C u d a   D r i v e r   ( i n v a l i d   a r g u m e n t )

**Comment by adam-andrzejczak** [comment]
Forcing core.globals.providers = ['CUDAExecutionProvider', 'CPUExecutionProvider'] solves this error, but now the program consumes enormous disc space - over 100 GB, i need to clean this up to confirm if the GPU is faster than CPU. Which seems not to be the case looking at task manager...

**Comment by s0md3v** [comment]
@adam-andrzejczak what consumes the disk space exactly? extracted frames?

**Comment by adam-andrzejczak** [comment]
No idea, around 100 GB is taken if picking up GPU option. It seems ['CUDAExecutionProvider', 'CPUExecutionProvider'] is a bit faster, 1 frame per second HD clip. CPU usage ~20%, GPU 60%, 44 GB RAM, 10 GB GPU ram + 2GB VRAM.

**Comment by Fictiverse** [comment]
Same here, it tell me that cuda is not installed :
`RuntimeError: **D:\a\_work\1\s\**onnxruntime\python\onnxruntime_pybind_state.cc:636 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.`

**Comment by adam-andrzejczak** [comment]
@s0md3v my page file is 191.6 GB while running the program :)

**Comment by adam-andrzejczak** [comment]
@Fictiverse do what the log says, installing cudnn requires manually putting stuff into env path, google it.

**Comment by s0md3v** [comment]
@adam-andrzejczak I have absolutely no idea what's going on.

I have an AMD 6900XT GPU and I'm able to process 30-200 frames per second. It is supposed to work even better on NVIDIA but I don't know what's up with onnxruntime's memory leaks. I looked at onnxruntime's github issues, it seems to be a common problem.

I hope you folks find a solution.

**Comment by adam-andrzejczak** [comment]
I will try to look. Now playing with 480p, much faster, memory usage is the same, but CPU and GPU % is low, 20% on average.

**Comment by Boomba12** [comment]
Has anyone encountered this?
win10

 copying insightface\thirdparty\face3d\mesh\cython\setup.py -> build\lib.win-amd64-cpython-38\insightface\thirdparty\face3d\mesh\cython
      running build_ext
      building 'insightface.thirdparty.face3d.mesh.cython.mesh_core_cython' extension
      C:\Users\User\AppData\Local\Temp\pip-build-env-iem09hr9\overlay\Lib\site-packages\setuptools\command\build_py.py:201: _Warning: Package 'insightface.thirdparty.face3d.mesh.cython' is absent from the `packages` configuration.
      !!
      
        check.warn(importable)
      C:\Users\User\AppData\Local\Temp\pip-build-env-iem09hr9\overlay\Lib\site-packages\setuptools\command\build_py.py:201: _Warning: Package 'insightface.data.images' is absent from the `packages` configuration.
      !!

 check.warn(importable)
      C:\Users\User\AppData\Local\Temp\pip-build-env-iem09hr9\overlay\Lib\site-packages\setuptools\command\build_py.py:201: _Warning: Package 'insightface.data.objects' is absent from the `packages` configuration.
      !!

 check.warn(importable)
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for insightface
Failed to build insightface
ERROR: Could not build wheels for insightface, which is required to install pyproject.toml-based projects

**Comment by henryruhs** [comment]
@Boomba12 The problems are actual described in your log... you can solve it by yourself

**Comment by henryruhs** [comment]
This thread has been spammed with too many different topics, please use Discord for instant help.
